CREATE DATABASE QLQUANAN
GO

USE QLQUANAN
GO

--create table
CREATE TABLE NHANVIEN
(
	MA char(10),
	USERNAME varchar(20),
	MATKHAU varchar(50),
	DIENTHOAI char(12),
	CHINHANH char(10),
	TRANGTHAI bit,
	LOAI int,
	PRIMARY KEY (MA)
)

CREATE TABLE DANHMUCMONAN
(
	MA char(10),
	TEN nvarchar(50),
	TRANGTHAI bit,
	PRIMARY KEY (MA)
)

CREATE TABLE MENUMONAN
(
	MA char(10),
	TEN nvarchar(50),
	TRANGTHAI bit,
	DANHMUC char(10),
	PRIMARY KEY (MA)
)

CREATE TABLE DANHMUCMONANCHINHANH
(
	CHINHANH char(10),
	DANHMUC char(10),
	TRANGTHAI bit
	PRIMARY KEY(CHINHANH, DANHMUC)
)

CREATE TABLE MENUCHINHANH
(
	CHINHANH char(10),
	MONAN char(10),
	GIATIEN int,
	TRANGTHAI bit
	PRIMARY KEY(CHINHANH, MONAN)
)
CREATE TABLE CHINHANH
(
	MA char(10),
	TEN nvarchar(50),
	DIACHI nvarchar(150),
	DIENTHOAI char(15),
	THANHPHO nvarchar(50),
	SOBAN int,
	PRIMARY KEY (MA)
)

CREATE TABLE CHIPHI
(
	MA char(10),
	CHINHANH char(10),
	NOIDUNG nvarchar(100),
	NGAY date,
	CHIPHI int,
	PRIMARY KEY (MA)
)

CREATE TABLE REPORT
(
	CHINHANH char(10),
	CHIPHI int,
	DOANHTHU int,
	SODONHANGTAIQUAN int,
	SODONHANGGIAODI int,
	SODONHANGTONGDAI int,
	SODONHANGONLINE int,
	NGAY Date,
	PRIMARY KEY (NGAY, CHINHANH)
)

CREATE TABLE KHACHHANG
(
	MA char(10),
	TEN nvarchar(50),
	DIENTHOAI char(15),
	SOLANMUA int,
	LANMUAGANNHAT date,
	PRIMARY KEY (MA)
)

CREATE TABLE BAN
(
	MA char(10),
	TRANGTHAI bit,
	CHINHANH char(10)
	PRIMARY KEY (MA)
)

CREATE TABLE HOADON
(
	MA char(10),
	KHACHHANG char(10),
	CHINHANH char(10),
	NHANVIEN char(10),
	BAN char(10),
	NGAY date,
	LOAI int, --mua ve, online,...
	CACMONAN varchar(1000),
	PRIMARY KEY (MA)
)

-- Add foreign key
ALTER TABLE REPORT
ADD CONSTRAINT FK_REPORT_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);
--
ALTER TABLE NhanVien
ADD CONSTRAINT FK_NHANVIEN_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE ChiPhi
ADD CONSTRAINT FK_ChiPhi_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE HoaDon
ADD CONSTRAINT FK_HOADON_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE MenuChiNhanh
ADD CONSTRAINT FK_MENUCHINHANH_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE DanhMucMonAnChiNhanh
ADD CONSTRAINT FK_DANHMUCMONANCHINHANH_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE Ban
ADD CONSTRAINT FK_Ban_CHINHANH
FOREIGN KEY (ChiNhanh) REFERENCES ChiNhanh(MA);

ALTER TABLE HoaDon
ADD CONSTRAINT FK_HOADON_KHACHHANG
FOREIGN KEY (KhachHang) REFERENCES KhachHang(MA);

ALTER TABLE HoaDon
ADD CONSTRAINT FK_HOADON_NHANVIEN
FOREIGN KEY (NhanVien) REFERENCES NhanVien(MA);

ALTER TABLE DanhMucMonAnChiNhanh
ADD CONSTRAINT FK_DANHMUCMONANCHINHANH_DANHMUCMONAN
FOREIGN KEY (DanhMuc) REFERENCES DanhMucMonAn(MA);

ALTER TABLE MenuChiNhanh
ADD CONSTRAINT FK_MENUCHINHANH_MENUMONAN
FOREIGN KEY (MonAn) REFERENCES MenuMonAn(MA);



--ALTER TABLE REPORT DROP CONSTRAINT FK_REPORT_CHINHANH

--insert data
INSERT INTO DANHMUCMONAN VALUES ('A104', N'Cá', 0);
INSERT INTO DANHMUCMONAN VALUES ('A105', N'Cơm', 0);
INSERT INTO DANHMUCMONAN VALUES ('A106', N'Lẩu', 1);
INSERT INTO DANHMUCMONAN VALUES ('A107', N'Chiên', 0);
INSERT INTO DANHMUCMONAN VALUES ('A108', N'Canh', 0);